# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('end-round/', views.end_round, name='end_round'),
    path('platform/', views.platform_home, name='platform_home'),
    path('platform/governance/', views.platform_governance, name='platform_governance'),
    path('platform/governance/publish/', views.platform_governance_publish, name='platform_governance_publish'),
    path('platform/governance/cancel/', views.platform_governance_cancel, name='platform_governance_cancel'),
    path('platform/governance/clickbait-detection/', views.platform_clickbait_detection, name='platform_clickbait_detection'),
    path('platform/governance/clickbait-detection/save/', views.platform_clickbait_detection_save, name='platform_clickbait_detection_save'),
    path('platform/governance/traffic-penalty/', views.platform_traffic_penalty, name='platform_traffic_penalty'),
    path('platform/governance/traffic-penalty/save/', views.platform_traffic_penalty_save, name='platform_traffic_penalty_save'),
    path('platform/governance/report/', views.platform_report, name='platform_report'),
    path('platform/governance/report/save/', views.platform_report_save, name='platform_report_save'),
    path('platform/governance/revenue-penalty/', views.platform_revenue_penalty, name='platform_revenue_penalty'),
    path('platform/governance/revenue-penalty/save/', views.platform_revenue_penalty_save, name='platform_revenue_penalty_save'),
    path('platform/round-result/', views.platform_round_result, name='platform_round_result'),
    path('platform/performance/', views.platform_performance, name='platform_performance'),
    path('platform/performance/apply/', views.platform_performance_apply, name='platform_performance_apply'),
    path('platform/performance/submit/', views.platform_performance_submit, name='platform_performance_submit'),
    path('regulator/', views.regulator_home, name='regulator_home'),
    path('regulator/special-action/', views.regulator_special_action, name='regulator_special_action'),
    path('regulator/special-action/submit/', views.regulator_special_action_submit, name='regulator_special_action_submit'),
    path('regulator/platform-patrol/', views.regulator_platform_patrol, name='regulator_platform_patrol'),
    path('regulator/platform-patrol/submit/', views.regulator_platform_patrol_submit, name='regulator_platform_patrol_submit'),
    path('regulator/platform-spot-check/<int:pk>/open/', views.platform_spot_check_open, name='platform_spot_check_open'),
    path('regulator/platform-spot-check/<int:pk>/', views.platform_spot_check_detail, name='platform_spot_check_detail'),
    path('writer/', views.writer_home, name='writer_home'),
    path('writer/start-article/', views.writer_start_article, name='writer_start_article'),
    path('writer/generate-titles/', views.writer_generate_titles, name='writer_generate_titles'),
    path('writer/select-title/', views.writer_select_title, name='writer_select_title'),
    path('writer/generate-bodies/', views.writer_generate_bodies, name='writer_generate_bodies'),
    path('writer/select-body/', views.writer_select_body, name='writer_select_body'),
    path('writer/article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('writer/history/', views.writer_article_history, name='writer_article_history'),
    path('writer/notices/', views.writer_notices, name='writer_notices'),
    path('writer/notices/<int:notice_id>/read/', views.writer_notice_read, name='writer_notice_read'),
    path('user/', views.user_home, name='user_home'),
    path('user/platform-check/', views.user_platform_check, name='user_platform_check'),
    path('user/switch-platform/', views.user_switch_platform, name='user_switch_platform'),
    path('user/browse/<int:platform_id>/', views.user_browse, name='user_browse'),
    path('user/article/<int:article_id>/', views.user_article_view, name='user_article_view'),
    path('user/article/<int:article_id>/like/', views.user_article_like, name='user_article_like'),
    path('user/article/<int:article_id>/collect/', views.user_article_collect, name='user_article_collect'),
    path('user/article/<int:article_id>/read-complete/', views.user_article_read_complete, name='user_article_read_complete'),
    path('user/article/<int:article_id>/follow/', views.user_article_follow, name='user_article_follow'),
    path('user/article/<int:article_id>/unfollow/', views.user_article_unfollow, name='user_article_unfollow'),
    path('user/article/<int:article_id>/report/', views.user_article_report, name='user_article_report'),
    path('user/article/<int:article_id>/comment/', views.user_article_add_comment, name='user_article_add_comment'),
]
