# Generated by Django 6.0.3 on 2026-03-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('账号', models.CharField(max_length=64, unique=True)),
                ('密码', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': '用户',
            },
        ),
        migrations.CreateModel(
            name='WriterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('账号', models.CharField(max_length=64, unique=True)),
                ('密码', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '写手',
                'verbose_name_plural': '写手',
                'db_table': '写手',
            },
        ),
    ]
