# Generated by Django 6.0.3 on 2026-03-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('写手账号', models.CharField(max_length=64)),
                ('标题', models.TextField(blank=True)),
                ('标题夸张度', models.IntegerField(blank=True, null=True)),
                ('正文', models.TextField(blank=True)),
                ('内容相关度', models.IntegerField(blank=True, null=True)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': '文章',
            },
        ),
    ]
