# Generated by Django 6.0.3 on 2026-03-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='已推送',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='收藏量',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='点击量',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='点赞量',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('内容', models.TextField()),
                ('评论者', models.CharField(blank=True, max_length=64)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('文章', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='评论列表', to='accounts.article')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': '评论',
            },
        ),
    ]
