# Generated by Django 6.0.3 on 2026-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_article_stats_and_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='所属平台',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='禁止登录截止时间',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
