# Generated by Django 6.0.3 on 2026-03-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_platform_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSwitchSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('用户编号', models.PositiveIntegerField()),
                ('切换前平台', models.IntegerField()),
                ('切换后平台', models.IntegerField()),
                ('轮次', models.PositiveIntegerField()),
                ('切换平台原因', models.TextField()),
            ],
            options={
                'verbose_name': '切换平台问卷调查',
                'verbose_name_plural': '切换平台问卷调查',
                'db_table': '切换平台问卷调查',
            },
        ),
        migrations.CreateModel(
            name='SimRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('当前轮次', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': '模拟轮次',
                'verbose_name_plural': '模拟轮次',
                'db_table': '模拟轮次',
            },
        ),
    ]
