# Generated by Django 6.0.3 on 2026-03-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_platform_switch_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimRound',
        ),
    ]
