# Generated by Django 6.0.3 on 2026-03-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_simround'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('写手账号', models.CharField(max_length=64)),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='关注写手列表', to='accounts.useraccount')),
            ],
            options={
                'verbose_name': '用户关注写手',
                'verbose_name_plural': '用户关注写手',
                'db_table': '用户关注写手',
                'unique_together': {('用户', '写手账号')},
            },
        ),
    ]
