# Generated by Django 6.0.3 on 2026-03-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_follow_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnfollowSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('用户编号', models.PositiveIntegerField()),
                ('写手账号', models.CharField(max_length=64)),
                ('当前轮次', models.PositiveIntegerField()),
                ('取关原因', models.TextField()),
                ('文章编号', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '取关/拉黑账号问卷调查',
                'verbose_name_plural': '取关/拉黑账号问卷调查',
                'db_table': '取关拉黑账号问卷调查',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='取关数',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='吸粉数',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='阅读完成量',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userfollowwriter',
            name='用户',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='关注列表', to='accounts.useraccount'),
        ),
    ]
