# Generated by Django 6.0.3 on 2026-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_article_stats_and_unfollow_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='粉丝数',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writeraccount',
            name='粉丝数',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
