# Generated by Django 6.0.3 on 2026-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_useraccount_粉丝数_to_关注数'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('账号', models.CharField(max_length=64, unique=True)),
                ('密码', models.CharField(max_length=128)),
                ('所属平台', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '平台账号',
                'verbose_name_plural': '平台账号',
                'db_table': '平台账号',
            },
        ),
    ]
