# Generated by Django 6.0.3 on 2026-03-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_platformaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('生效轮次起', models.PositiveIntegerField(default=1)),
                ('生效轮次止', models.PositiveIntegerField(blank=True, null=True)),
                ('点击率权重', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('收藏率权重', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('阅读完成率权重', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('平台粉丝数权重', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('利润展示窗口轮数', models.PositiveIntegerField(default=4)),
                ('备注', models.TextField(blank=True)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '平台利润权重配置',
                'verbose_name_plural': '平台利润权重配置',
                'db_table': '平台利润权重配置',
                'ordering': ['-创建时间', '-id'],
            },
        ),
    ]
