# Generated by Django 6.0.3 on 2026-03-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profitweightconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRoundProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('平台', models.IntegerField()),
                ('轮次', models.PositiveIntegerField()),
                ('利润', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('同比增减', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('因子快照', models.JSONField(blank=True, default=dict)),
                ('监管成本档位', models.CharField(blank=True, max_length=32)),
                ('监管成本', models.IntegerField(default=0)),
                ('财务分析', models.JSONField(blank=True, default=dict)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('权重配置', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='利润记录', to='accounts.profitweightconfig')),
            ],
            options={
                'verbose_name': '平台每轮利润',
                'verbose_name_plural': '平台每轮利润',
                'db_table': '平台每轮利润',
                'ordering': ['-轮次', '平台', '-id'],
                'unique_together': {('平台', '轮次')},
            },
        ),
    ]
