# Generated by Django 6.0.3 on 2026-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_platformroundprofit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformGovernanceMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('平台', models.IntegerField()),
                ('轮次', models.PositiveIntegerField()),
                ('措施类型', models.CharField(choices=[('account_health_rule', '账号健康分规则')], max_length=64)),
                ('措施内容', models.JSONField(blank=True, default=dict)),
                ('发布人账号', models.CharField(blank=True, max_length=64)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '平台治理措施记录',
                'verbose_name_plural': '平台治理措施记录',
                'db_table': '平台治理措施记录',
                'ordering': ['-轮次', '-创建时间', '-id'],
            },
        ),
    ]
