# Generated by Django 6.0.3 on 2026-03-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_platformgovernancemeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPerformanceScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('平台', models.IntegerField()),
                ('生效轮次', models.PositiveIntegerField()),
                ('方案编号', models.CharField(choices=[('S1_balanced', '方案1：均衡'), ('S2_click_first', '方案2：点击优先'), ('S3_quality_first', '方案3：质量优先')], max_length=64)),
                ('方案内容', models.JSONField(blank=True, default=dict)),
                ('发布人账号', models.CharField(blank=True, max_length=64)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '平台绩效方案记录',
                'verbose_name_plural': '平台绩效方案记录',
                'db_table': '平台绩效方案记录',
                'ordering': ['-生效轮次', '-创建时间', '-id'],
            },
        ),
    ]
