# Generated by Django 6.0.3 on 2026-03-31 08:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_platformperformancescheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHealthLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('生效轮次起', models.PositiveIntegerField(default=1)),
                ('生效轮次止', models.PositiveIntegerField(blank=True, null=True)),
                ('下界开', models.IntegerField(default=0)),
                ('上界闭', models.IntegerField(default=100)),
                ('可推流比例', models.DecimalField(decimal_places=4, default=Decimal('0.7000'), max_digits=6)),
                ('排序', models.PositiveIntegerField(default=0)),
                ('备注', models.TextField(blank=True)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '账号健康分档位配置',
                'verbose_name_plural': '账号健康分档位配置',
                'db_table': '账号健康分档位配置',
                'ordering': ['排序', '下界开', '上界闭', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WriterHealthScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('写手账号', models.CharField(max_length=64)),
                ('轮次', models.PositiveIntegerField()),
                ('文章编号', models.PositiveIntegerField(blank=True, null=True)),
                ('变更值', models.IntegerField()),
                ('原因', models.CharField(blank=True, max_length=128)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '写手健康分变更审计',
                'verbose_name_plural': '写手健康分变更审计',
                'db_table': '写手健康分变更审计',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.AddField(
            model_name='platformgovernancemeasure',
            name='取消轮次',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformgovernancemeasure',
            name='生效轮次',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='writeraccount',
            name='健康分',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='WriterNoticeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('写手账号', models.CharField(max_length=64)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('通知', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='已读记录', to='accounts.platformgovernancemeasure')),
            ],
            options={
                'verbose_name': '写手通知已读',
                'verbose_name_plural': '写手通知已读',
                'db_table': '写手通知已读',
                'ordering': ['-read_at', '-id'],
                'unique_together': {('写手账号', '通知')},
            },
        ),
    ]
