# Generated by Django 6.0.3 on 2026-04-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_accounthealthlevelconfig_writerhealthscorelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformgovernancemeasure',
            name='config_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profitweightconfig',
            name='平台',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profitweightconfig',
            name='监管成本权重',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profitweightconfig',
            name='配置人',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profitweightconfig',
            name='配置时间',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformgovernancemeasure',
            name='措施类型',
            field=models.CharField(choices=[('account_health_rule', '账号健康分规则'), ('clickbait_detection', '标题党检测'), ('user_report', '用户举报机制'), ('traffic_penalty', '流量惩罚'), ('revenue_penalty', '收益惩罚'), ('performance_rule', '绩效规则')], max_length=64),
        ),
        migrations.CreateModel(
            name='PlatformCycleProfitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('cycle_index', models.PositiveIntegerField()),
                ('cycle_start_round', models.PositiveIntegerField()),
                ('cycle_end_round', models.PositiveIntegerField()),
                ('total_click', models.PositiveIntegerField(default=0)),
                ('total_collect', models.PositiveIntegerField(default=0)),
                ('total_finish', models.PositiveIntegerField(default=0)),
                ('fans_snapshot', models.PositiveIntegerField(default=0)),
                ('supervision_cost_level', models.CharField(blank=True, max_length=32)),
                ('supervision_cost_value', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('profit_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('profit_prev_cycle', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('weight_config_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': '平台周期利润记录',
                'verbose_name_plural': '平台周期利润记录',
                'db_table': '平台周期利润记录',
                'ordering': ['-cycle_index', 'platform_id', '-id'],
                'unique_together': {('platform_id', 'cycle_index')},
            },
        ),
        migrations.DeleteModel(
            name='PlatformRoundProfit',
        ),
    ]
