# Generated by Django 6.0.3 on 2026-04-12 08:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_platformgovernancemeasure_config_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='clickbait_detected_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_clickbait',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='method_auto_rule',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='method_user',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='report_count_current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writeraccount',
            name='health_tier',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='writeraccount',
            name='健康分最近更新轮次',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writeraccount',
            name='推流系数',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5),
        ),
    ]
