# Generated by Django 6.0.3 on 2026-04-12 08:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_article_clickbait_detected_at_article_is_clickbait_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickbaitDetectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('判定阈值', models.IntegerField(default=2)),
                ('判定概率值', models.DecimalField(decimal_places=2, default=Decimal('0.80'), max_digits=3)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '标题党检测配置',
                'verbose_name_plural': '标题党检测配置',
                'db_table': '标题党检测配置',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TrafficPenaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('降权系数alpha', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=3)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '流量惩罚配置',
                'verbose_name_plural': '流量惩罚配置',
                'db_table': '流量惩罚配置',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('轮次', models.PositiveIntegerField()),
                ('基础流量', models.PositiveIntegerField(default=0)),
                ('penalty_applied', models.BooleanField(default=False)),
                ('penalty_coefficient', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('health_tier_coefficient', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('最终流量', models.PositiveIntegerField(default=0)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('文章', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='流量记录', to='accounts.article')),
            ],
            options={
                'verbose_name': '文章流量记录',
                'verbose_name_plural': '文章流量记录',
                'db_table': '文章流量记录',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClickbaitDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('轮次', models.PositiveIntegerField()),
                ('平台', models.IntegerField()),
                ('标题夸张度X', models.IntegerField()),
                ('内容相关度Y', models.IntegerField()),
                ('自动检测是否执行', models.BooleanField(default=False)),
                ('检测结果', models.BooleanField(blank=True, null=True)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('文章', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='标题党检测结果', to='accounts.article')),
            ],
            options={
                'verbose_name': '标题党检测结果',
                'verbose_name_plural': '标题党检测结果',
                'db_table': '标题党检测结果',
                'ordering': ['-创建时间', '-id'],
            },
        ),
    ]
