# Generated by Django 6.0.3 on 2026-04-12 08:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_clickbaitdetectionconfig_trafficpenaltyconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenuePenaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('惩罚系数beta', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=3)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '收益惩罚配置',
                'verbose_name_plural': '收益惩罚配置',
                'db_table': '收益惩罚配置',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('举报触发阈值', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=3)),
                ('审核方式', models.CharField(choices=[('auto', '自动审核'), ('manual', '人工审核')], default='auto', max_length=20)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户举报配置',
                'verbose_name_plural': '用户举报配置',
                'db_table': '用户举报配置',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('举报人', models.CharField(max_length=100)),
                ('举报轮次', models.PositiveIntegerField()),
                ('审核状态', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核驳回')], default='pending', max_length=20)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('文章', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='举报记录', to='accounts.article')),
            ],
            options={
                'verbose_name': '用户举报记录',
                'verbose_name_plural': '用户举报记录',
                'db_table': '用户举报记录',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRevenueSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('写手账号', models.CharField(max_length=100)),
                ('轮次', models.PositiveIntegerField()),
                ('点击量', models.PositiveIntegerField(default=0)),
                ('阅读完成量', models.PositiveIntegerField(default=0)),
                ('收藏量', models.PositiveIntegerField(default=0)),
                ('满意度均分', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('w1', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('w2', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('w3', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('w4', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('原始收益', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('penalty_applied', models.BooleanField(default=False)),
                ('penalty_coefficient', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('最终收益', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('结算时间', models.DateTimeField(auto_now_add=True)),
                ('文章', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='收益结算记录', to='accounts.article')),
            ],
            options={
                'verbose_name': '文章收益结算',
                'verbose_name_plural': '文章收益结算',
                'db_table': '文章收益结算',
                'ordering': ['-结算时间', '-id'],
            },
        ),
    ]
