# Generated by Django 6.0.3 on 2026-04-12 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_revenuepenaltyconfig_userreportconfig_articlereport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHealthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('初始健康分', models.IntegerField(default=100)),
                ('每次违规扣减分值', models.IntegerField(default=10)),
                ('是否启用恢复机制', models.BooleanField(default=False)),
                ('恢复所需连续无违规轮次', models.IntegerField(default=3)),
                ('每次恢复分值', models.IntegerField(default=5)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '账号健康分配置',
                'verbose_name_plural': '账号健康分配置',
                'db_table': '账号健康分配置',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.AddField(
            model_name='accounthealthlevelconfig',
            name='平台',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounthealthlevelconfig',
            name='档位标签',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='writerhealthscorelog',
            name='event_type',
            field=models.CharField(choices=[('violation', '违规扣分'), ('recovery', '信用恢复')], default='violation', max_length=20),
        ),
        migrations.AddField(
            model_name='accounthealthlevelconfig',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='档位列表', to='accounts.accounthealthconfig'),
        ),
    ]
