# Generated by Django 6.0.3 on 2026-04-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_accounthealthconfig_accounthealthlevelconfig_平台_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformperformancescheme',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('active', '已生效'), ('cancelled', '已取消')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='platformperformancescheme',
            name='w1_click',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='platformperformancescheme',
            name='w2_finish',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='platformperformancescheme',
            name='w3_collect',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='platformperformancescheme',
            name='w4_satisfaction',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='platformperformancescheme',
            name='管理员确认时间',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformperformancescheme',
            name='管理员确认账号',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
