# Generated by Django 6.0.3 on 2026-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_platformperformancescheme_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthealthconfig',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('active', '已生效'), ('rejected', '已驳回')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='accounthealthconfig',
            name='提交人账号',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='accounthealthconfig',
            name='管理员确认时间',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounthealthconfig',
            name='管理员确认账号',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clickbaitdetectionconfig',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('active', '已生效'), ('rejected', '已驳回')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='clickbaitdetectionconfig',
            name='提交人账号',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='clickbaitdetectionconfig',
            name='管理员确认时间',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clickbaitdetectionconfig',
            name='管理员确认账号',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='platformgovernancemeasure',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('active', '已生效'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='platformgovernancemeasure',
            name='管理员确认时间',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformgovernancemeasure',
            name='管理员确认账号',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='revenuepenaltyconfig',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('active', '已生效'), ('rejected', '已驳回')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='revenuepenaltyconfig',
            name='提交人账号',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='revenuepenaltyconfig',
            name='管理员确认时间',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenuepenaltyconfig',
            name='管理员确认账号',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trafficpenaltyconfig',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('active', '已生效'), ('rejected', '已驳回')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='trafficpenaltyconfig',
            name='提交人账号',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trafficpenaltyconfig',
            name='管理员确认时间',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficpenaltyconfig',
            name='管理员确认账号',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userreportconfig',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('active', '已生效'), ('rejected', '已驳回')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='userreportconfig',
            name='提交人账号',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userreportconfig',
            name='管理员确认时间',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreportconfig',
            name='管理员确认账号',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
