# Generated by Django 6.0.3 on 2026-04-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_accounthealthconfig_status_accounthealthconfig_提交人账号_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickbaitdetectionconfig',
            name='判定概率值',
        ),
        migrations.RemoveField(
            model_name='clickbaitdetectionconfig',
            name='判定阈值',
        ),
        migrations.AddField(
            model_name='clickbaitdetectionconfig',
            name='内容相关度阈值Y',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='clickbaitdetectionconfig',
            name='标题夸张度阈值X',
            field=models.IntegerField(default=4),
        ),
    ]
