# Generated by Django 6.0.3 on 2026-04-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_clickbaitdetectionconfig_判定概率值_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationActionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('行动编号', models.CharField(max_length=32, unique=True)),
                ('当前轮次', models.PositiveIntegerField()),
                ('整治平台编号列表', models.JSONField(blank=True, default=list)),
                ('整治平台名称列表', models.JSONField(blank=True, default=list)),
                ('整治持续轮次', models.PositiveIntegerField(default=8)),
                ('整治原因', models.CharField(max_length=64)),
                ('其他原因说明', models.TextField(blank=True)),
                ('申请状态', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20)),
                ('申请人账号', models.CharField(blank=True, max_length=64)),
                ('管理员确认账号', models.CharField(blank=True, max_length=100)),
                ('管理员确认时间', models.DateTimeField(blank=True, null=True)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '监管专项行动申请表',
                'verbose_name_plural': '监管专项行动申请表',
                'db_table': '监管专项行动申请表',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RegulatorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('账号', models.CharField(max_length=64, unique=True)),
                ('密码', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '监管机构账号',
                'verbose_name_plural': '监管机构账号',
                'db_table': '监管机构账号',
            },
        ),
        migrations.CreateModel(
            name='RegulationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('行动编号', models.CharField(max_length=32)),
                ('当前轮次', models.PositiveIntegerField()),
                ('整治平台编号', models.IntegerField()),
                ('整治平台名称', models.CharField(max_length=64)),
                ('整治持续轮次', models.PositiveIntegerField(default=8)),
                ('开始轮次', models.PositiveIntegerField()),
                ('结束轮次', models.PositiveIntegerField()),
                ('整治原因', models.CharField(max_length=64)),
                ('其他原因说明', models.TextField(blank=True)),
                ('状态', models.CharField(choices=[('active', '整治中'), ('finished', '已完成')], default='active', max_length=20)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('申请记录', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='正式行动列表', to='accounts.regulationactionapplication')),
            ],
            options={
                'verbose_name': '监管专项行动表',
                'verbose_name_plural': '监管专项行动表',
                'db_table': '监管专项行动表',
                'ordering': ['-创建时间', '-id'],
            },
        ),
    ]
