# Generated by Django 6.0.3 on 2026-04-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_regulationactionapplication_regulatoraccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSpotCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('行动编号', models.CharField(max_length=32)),
                ('整治平台编号', models.IntegerField()),
                ('整治平台名称', models.CharField(max_length=64)),
                ('是否查看', models.BooleanField(default=False)),
                ('专项行动', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='抽查结果', to='accounts.regulationaction')),
            ],
            options={
                'verbose_name': '平台抽查结果表',
                'verbose_name_plural': '平台抽查结果表',
                'db_table': '平台抽查结果表',
                'ordering': ['-id'],
            },
        ),
    ]
