# Generated by Django 6.0.3 on 2026-04-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_platform_patrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpatrolresult',
            name='执行轮次',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
