# Generated by Django 6.0.3 on 2026-04-18 17:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_admin_base_config(apps, schema_editor):
    AdminBaseConfig = apps.get_model('accounts', 'AdminBaseConfig')
    AdminBaseConfig.objects.get_or_create(
        pk=1,
        defaults={'自动巡查比例': Decimal('0.5')},
    )


def unseed_admin_base_config(apps, schema_editor):
    AdminBaseConfig = apps.get_model('accounts', 'AdminBaseConfig')
    AdminBaseConfig.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_platform_patrol_exec_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('自动巡查比例', models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=5)),
                ('更新时间', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '管理员基础配置',
                'verbose_name_plural': '管理员基础配置',
                'db_table': '管理员基础配置表',
            },
        ),
        migrations.RunPython(seed_admin_base_config, unseed_admin_base_config),
        migrations.AddField(
            model_name='platformpatrolresult',
            name='专项行动',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='配套巡查结果', to='accounts.regulationaction'),
        ),
        migrations.AddField(
            model_name='platformpatrolresult',
            name='巡查类型',
            field=models.CharField(choices=[('manual', '手动'), ('auto', '自动')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='regulationaction',
            name='配套自动巡查已执行',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformpatrolresult',
            name='申请记录',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='巡查结果', to='accounts.platformpatrolapplication', unique=True),
        ),
    ]
