# Generated by Django 6.0.3 on 2026-04-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_regulation_auto_patrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformpatrolresult',
            name='申请记录',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='巡查结果', to='accounts.platformpatrolapplication'),
        ),
    ]
