# Generated by Django 6.0.3 on 2026-04-18 18:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_platform_patrol_application_onetoone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatorFineApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('申请轮次', models.PositiveIntegerField()),
                ('平台编号', models.IntegerField()),
                ('平台名称', models.CharField(max_length=64)),
                ('罚款档次', models.CharField(choices=[('light', '轻微'), ('basic', '基础'), ('medium', '中等'), ('strict', '严格')], max_length=16)),
                ('申请状态', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20)),
                ('申请人账号', models.CharField(blank=True, max_length=64)),
                ('管理员确认账号', models.CharField(blank=True, max_length=100)),
                ('管理员确认时间', models.DateTimeField(blank=True, null=True)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '监管机构罚款申请表',
                'verbose_name_plural': '监管机构罚款申请表',
                'db_table': '监管机构罚款申请表',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.AddField(
            model_name='adminbaseconfig',
            name='罚款严格监管成本',
            field=models.DecimalField(decimal_places=6, default=Decimal('-8'), max_digits=18),
        ),
        migrations.AddField(
            model_name='adminbaseconfig',
            name='罚款中等监管成本',
            field=models.DecimalField(decimal_places=6, default=Decimal('-4'), max_digits=18),
        ),
        migrations.AddField(
            model_name='adminbaseconfig',
            name='罚款基础监管成本',
            field=models.DecimalField(decimal_places=6, default=Decimal('-2'), max_digits=18),
        ),
        migrations.AddField(
            model_name='adminbaseconfig',
            name='罚款轻微监管成本',
            field=models.DecimalField(decimal_places=6, default=Decimal('-1'), max_digits=18),
        ),
        migrations.CreateModel(
            name='RegulatorFineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('执行轮次', models.PositiveIntegerField()),
                ('平台编号', models.IntegerField()),
                ('平台名称', models.CharField(max_length=64)),
                ('罚款档次', models.CharField(choices=[('light', '轻微'), ('basic', '基础'), ('medium', '中等'), ('strict', '严格')], max_length=16)),
                ('监管成本数值', models.DecimalField(decimal_places=6, help_text='审批时快照，与监管成本权重相乘计入周期利润', max_digits=18)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('申请记录', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='罚款记录', to='accounts.regulatorfineapplication')),
            ],
            options={
                'verbose_name': '监管机构罚款记录表',
                'verbose_name_plural': '监管机构罚款记录表',
                'db_table': '监管机构罚款记录表',
                'ordering': ['-创建时间', '-id'],
            },
        ),
    ]
