# Generated by Django 6.0.4 on 2026-04-19 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_regulator_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterGovernanceNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('写手账号', models.CharField(max_length=64)),
                ('是否已读', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('投递轮次', models.PositiveIntegerField()),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='写手通知记录', to='accounts.platformgovernancemeasure')),
            ],
            options={
                'verbose_name': '写手治理通知收件箱',
                'verbose_name_plural': '写手治理通知收件箱',
                'db_table': '写手治理通知收件箱',
                'ordering': ['-投递轮次', '-id'],
                'constraints': [models.UniqueConstraint(fields=('写手账号', 'measure'), name='uniq_writer_governance_notice')],
            },
        ),
    ]
