# Generated by Django 6.0.4 on 2026-04-19 14:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_performance_three_weights_writing_coef'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoraccount',
            name='负责平台编号列表',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='adminbaseconfig',
            name='写作成本映射',
            field=models.JSONField(blank=True, default=accounts.models.default_writing_cost_map),
        ),
    ]
