# Generated by Django 6.0.4 on 2026-04-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_regulator_default_jurisdiction_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAnomalyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('轮次', models.PositiveIntegerField()),
                ('事件', models.CharField(default='user_report', max_length=32)),
                ('平台编号', models.IntegerField()),
                ('文章id', models.PositiveIntegerField()),
                ('实时更新举报数', models.IntegerField()),
                ('结算统计举报数', models.IntegerField()),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '举报异常记录',
                'verbose_name_plural': '举报异常记录',
                'db_table': '举报异常记录',
                'ordering': ['-创建时间', '-id'],
                'constraints': [models.UniqueConstraint(fields=('轮次', '事件', '平台编号', '文章id'), name='uniq_report_anomaly_round_event_platform_article')],
            },
        ),
    ]
