# Generated by Django 6.0.4 on 2026-04-20 05:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_reportanomalyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSelfPatrolApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('申请轮次', models.PositiveIntegerField()),
                ('平台编号', models.IntegerField()),
                ('平台名称', models.CharField(max_length=64)),
                ('巡查比例', models.DecimalField(decimal_places=4, max_digits=5)),
                ('起始轮次', models.PositiveIntegerField()),
                ('终止轮次', models.PositiveIntegerField()),
                ('申请状态', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20)),
                ('申请人账号', models.CharField(blank=True, max_length=64)),
                ('管理员确认账号', models.CharField(blank=True, max_length=100)),
                ('管理员确认时间', models.DateTimeField(blank=True, null=True)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '平台巡查申请表',
                'verbose_name_plural': '平台巡查申请表',
                'db_table': '平台巡查申请表',
                'ordering': ['-创建时间', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSelfPatrolResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('平台编号', models.IntegerField()),
                ('平台名称', models.CharField(max_length=64)),
                ('巡查比例', models.DecimalField(decimal_places=4, max_digits=5)),
                ('起始轮次', models.PositiveIntegerField()),
                ('终止轮次', models.PositiveIntegerField()),
                ('用户数', models.PositiveIntegerField(default=0)),
                ('抽查文章数', models.PositiveIntegerField(default=0)),
                ('抽查文章列表', models.JSONField(blank=True, default=list)),
                ('标题党率', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=7)),
                ('执行轮次', models.PositiveIntegerField(default=1)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('申请记录', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='巡查结果', to='accounts.platformselfpatrolapplication')),
            ],
            options={
                'verbose_name': '平台巡查行动表',
                'verbose_name_plural': '平台巡查行动表',
                'db_table': '平台巡查行动表',
                'ordering': ['-创建时间', '-id'],
            },
        ),
    ]
