# Generated by Django 6.0.3 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_platform_self_patrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="writerhealthscorelog",
            name="已确认",
            field=models.BooleanField(default=False),
        ),
    ]

