# Generated by Django 6.0.5 on 2026-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_writerhealthscorelog_已确认'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='写手账号',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='轮次',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='所属平台',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['轮次', '写手账号'], name='文章_轮次_beef25_idx'),
        ),
    ]
