# Generated by Django 6.0.5 on 2026-05-21 08:58

from django.db import migrations, models


def _backfill_platform(apps, schema_editor):
    """回填已有 ArticlePush / ArticlePushDetail 的平台字段。"""
    ArticlePush = apps.get_model('accounts', 'ArticlePush')
    ArticlePushDetail = apps.get_model('accounts', 'ArticlePushDetail')
    Article = apps.get_model('accounts', 'Article')
    WriterAccount = apps.get_model('accounts', 'WriterAccount')

    # 构建 写手账号 → 所属平台 的映射
    writer_platform_map = dict(
        WriterAccount.objects.values_list('账号', '所属平台')
    )

    # 回填 ArticlePush
    push_ids_to_update = []
    for push in ArticlePush.objects.filter(平台=0).only('id', '文章_id'):
        article = Article.objects.only('写手账号').filter(pk=push.文章_id).first()
        if article:
            platform = writer_platform_map.get(article.写手账号, 0)
            push.平台 = platform
            push_ids_to_update.append(push)

    if push_ids_to_update:
        ArticlePush.objects.bulk_update(push_ids_to_update, ['平台'], batch_size=500)

    # 回填 ArticlePushDetail
    detail_ids_to_update = []
    for detail in ArticlePushDetail.objects.filter(平台=0).only('id', '文章_id'):
        article = Article.objects.only('写手账号').filter(pk=detail.文章_id).first()
        if article:
            platform = writer_platform_map.get(article.写手账号, 0)
            detail.平台 = platform
            detail_ids_to_update.append(detail)

    if detail_ids_to_update:
        ArticlePushDetail.objects.bulk_update(detail_ids_to_update, ['平台'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_article_写手账号_alter_article_轮次_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepush',
            name='平台',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlepushdetail',
            name='平台',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(_backfill_platform, migrations.RunPython.noop),
    ]
